name: Run Postman Tests and Build Docker
permissions:
  pull-requests: write

on:
  push:
    branches:
      - main

jobs:
  run-newman-tests:
    name: Postman Tests
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Create directory for test artifacts
      - name: Create directory for reports
        run: mkdir -p testArtifacts

      # Step 3: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Step 4: Install Newman and Reporter
      - name: Install Newman and HTML Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      # Step 5: Run Newman Tests
      - name: Run Postman Tests with Newman
        run: |
          newman run "PostmanApiTesting/JsonPlaceHolder.postman_collection.json" \
            -e "PostmanApiTesting/TestVariable.postman_environment.json" \
            -d "./data/PostmanAssignment.csv" \
            -r cli,htmlextra \
            --reporter-htmlextra-export testArtifacts/newman-report.html

      # Step 6: Upload Newman Report
      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: Newman Test Report
          path: testArtifacts/newman-report.html

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: run-newman-tests

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build Docker Image
      - name: Build Docker image
        run: docker build -t rahulknoldus/postmandemotest:${{ github.sha }} .

      # Step 4: Push Docker Image
      - name: Push Docker image
        run: docker push rahulknoldus/postmandemotest:${{ github.sha }}
