name: Run Postman Tests and Build Docker
permissions:
  pull-requests: write

on:
  push:
    branches:
      - main

jobs:
  run-newman-tests:
    name: Postman Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create directory for reports
        run: mkdir -p testArtifacts

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Newman and HTML Reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra

      - name: Run Postman Tests with Newman
        run: |
          newman run "PostmanApiTesting/JsonPlaceHolder.postman_collection.json" \
            -e "PostmanApiTesting/TestVariable.postman_environment.json" \
            -d "./data/PostmanAssignment.csv" \
            -r cli,htmlextra \
            --reporter-htmlextra-export testArtifacts/newman-report.html

      - name: Upload Test Results
        uses: actions/upload-artifact@v3
        with:
          name: Newman Test Report
          path: testArtifacts/newman-report.html

      - name: Post Comment to PR with Report Link
        if: ${{ github.event_name == 'pull_request' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: Postman Test Results
          append: true
          message: |
            ### Postman Test Results
            A detailed HTML report has been generated for this PR. You can download it from the link below:

            [Download Newman HTML Report](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}#artifact)

  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: run-newman-tests

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t rahulknoldus/postmandemotest:${{ github.sha }} .

      - name: Push Docker image
        run: docker push rahulknoldus/postmandemotest:${{ github.sha }}
